// Generated for Phase 3 anti-cheat (sub-phase 3.2) — minimum physical
// completion time per drill, from rep counts + 5s rest per rep.
// Methodology + full table: PHASE3_DEVIATIONS.md Appendix A.
export const DRILL_MIN_MINUTES: Record<string, number> = {
  'The Tempo Towel Drill': 6,
  'The Gate Drill — Driver': 5,
  'The Slow Motion Drill': 3.5,
  'The Tee Height Ladder': 3.5,
  'The Foot Together Drill': 3.5,
  'The Alignment Stick Path Drill': 5,
  'The Impact Bag Drill': 5,
  'The 3 Ball Progression': 3.5,
  'The L to L Drill': 5,
  'The Eyes Closed Drill': 2.5,
  'The Step Through Drill': 3.5,
  'The 9 Shot Shape Drill': 2,
  'The Speed Training Drill': 2,
  'The Divot Board Drill': 5,
  'The Pump Drill': 3.5,
  'The Yardage Marker Drill': 2.5,
  'The Coin Drill': 5,
  'The Headcover Drill': 5,
  'The Ball Position Ladder': 3.5,
  'The Towel Under Lead Arm Drill': 5,
  'The Miss Drill': 2.5,
  'The Half Swing Compression Drill': 7.5,
  'The Knockdown Drill': 3.5,
  'The Random Club Drill': 3.5,
  'The One Handed Drill': 7.5,
  'The Par 3 Simulation Drill': 2,
  'The Landing Spot Drill': 4.5,
  'The Bump and Run Drill': 4.5,
  'The No Wristed Chip Drill': 4.5,
  'The Fringe Ladder Drill': 4.5,
  'The Bunker Line Drill': 9,
  'The Towel Drill — Short Game': 4.5,
  'The Clock Drill — Wedges': 3.5,
  'The Flop Shot Progression': 3.5,
  'The Up and Down Challenge': 2,
  'The One Club Challenge': 2,
  'The Wet Towel Lie Drill': 3.5,
  'The Spin Control Drill': 4.5,
  'The Pressure Chip Off': 2,
  'The Gate Drill — Putting': 6.5,
  'The Coin Putting Drill': 4,
  'The 3 Foot Circle Drill': 5,
  'The Metronome Drill': 4,
  'The One Hand Putting Drill': 6.5,
  'The Pre-Round Routine Putt': 3,
  'The Eyes Closed Putting Drill': 4,
  'The Ladder Drill — Putting': 2.5,
  'The Gate and String Drill': 6.5,
  'The Breaking Putt Reading Drill': 4,
  'The 100 Putt Challenge': 21.5,
  'The Tee in Ground Drill': 6.5,
  'The Pressure 18 Hole Putting Round': 3.5,
  'The Hip 90-90 Stretch': 2,
  'The Thoracic Spine Rotation': 3,
  'The Glute Bridge': 6.5,
  'The Single Leg Balance Drill': 2,
  'The Wrist and Forearm Strengthening Routine': 2,
  'The Medicine Ball Rotation Throw': 4.5,
  'The Pallof Press': 5,
  'The Lateral Band Walk': 6.5,
  'The Romanian Deadlift': 4.5,
  'The Cable or Band Wood Chop': 5,
  'The Club Selection Audit': 3,
  'The Layup Decision Drill': 3,
  'The Pre-Shot Routine Builder': 6.5,
  'The Trouble Shot Library': 8,
  'The Wind Adjustment Drill': 10,
  'The Miss Side Drill': 3,
  'The Bogey Avoidance Drill': 6,
  'The Par 18 Strategy Game': 6,
};
