import WelcomeNav from '@/components/welcome/WelcomeNav';
import WelcomeFooter from '@/components/welcome/WelcomeFooter';

const sections = [
  {
    title: 'Agreement to Terms',
    content: 'By accessing and using the Caddie AI Service, you agree to be bound by these Terms. If you do not agree with any part, please do not use the Service.',
  },
  {
    title: 'Description of Service',
    content: 'Caddie AI provides an AI-powered golf coaching platform that includes personalized practice plans, performance tracking, competitive leaderboards, and an AI coach available 24/7.',
  },
  {
    title: 'Accounts',
    content: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You agree to provide accurate information and notify us immediately of unauthorized access.',
  },
  {
    title: 'Subscriptions and Billing',
    content: 'Caddie AI offers subscription plans that unlock features of the service. Subscription pricing is available on our website. New users receive a free trial period before billing begins.',
    items: [
      'Billing: Charges occur on the same day each period unless you cancel',
      'Failed Payments: If payment fails, we will attempt to charge again within 5 business days',
      'Cancellation: Cancel anytime from your account settings; no refunds for partial periods',
      'Price Changes: We may change prices with 30 days notice',
    ],
  },
  {
    title: 'Referral Program',
    content: 'Users can refer friends via unique referral codes. When a referred friend completes their first payment, the referrer receives one free month of service credited to their account. There is no limit on referrals earned.',
  },
  {
    title: 'Leaderboard and Monthly Prize',
    content: 'Leaderboards are updated monthly and rank users by activity and improvement scores. The top-ranked user at month end receives one free month of service. Rankings are reset monthly; all-time records are preserved in the Hall of Fame.',
  },
  {
    title: 'Acceptable Use',
    content: 'You agree not to:',
    items: [
      'Use the Service for illegal purposes',
      'Harass, abuse, or defame others',
      'Reverse engineer or access underlying systems',
      'Spam or send unsolicited communications',
      'Share false or fabricated golf data to manipulate leaderboards',
    ],
  },
  {
    title: 'AI-Generated Content',
    content: 'All coaching advice, drills, and recommendations are generated by AI and provided "as-is". While we strive for accuracy, we do not guarantee that all content is suitable for your specific skill level or circumstances. Users should exercise judgment and consult golf professionals for complex issues.',
  },
  {
    title: 'Intellectual Property',
    content: 'All content, features, and functionality are owned by Caddie AI. You may not reproduce, distribute, or transmit any content without permission. User-submitted data (golf scores, messages) remains your property, but you grant us a license to use it to improve the Service.',
  },
  {
    title: 'Disclaimer of Warranties',
    content: 'THE SERVICE IS PROVIDED "AS-IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. GOLF PERFORMANCE IMPROVEMENTS ARE NOT GUARANTEED.',
  },
  {
    title: 'Limitation of Liability',
    content: 'TO THE FULLEST EXTENT PERMITTED BY LAW, CADDIE AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.',
  },
  {
    title: 'Governing Law',
    content: 'These Terms are governed by the laws of the State of Michigan, without regard to its conflict of law principles.',
  },
  {
    title: 'Changes to Terms',
    content: 'We may update these Terms at any time. Continued use of the Service constitutes acceptance of revised terms.',
  },
  {
    title: 'Termination',
    content: 'We may terminate your account if you violate these Terms or engage in harmful behavior. Upon termination, your access is revoked and no refunds are issued.',
  },
  {
    title: 'Contact Us',
    content: 'For questions about these Terms, contact us at support@caddieaiapp.com.',
  },
];

export default function Terms() {
  return (
    <div style={{ backgroundColor: '#1a2e1a', color: '#f9f9f7', minHeight: '100vh' }} className="flex flex-col">
      <WelcomeNav />
      
      <main className="flex-1 pt-24 md:pt-32 pb-20 px-6 md:px-12">
        <div className="max-w-4xl mx-auto">
          <h1 className="font-serif font-bold text-4xl md:text-5xl mb-2">Terms of Service</h1>
          <p className="text-white/60 text-sm mb-12">Last updated: April 2026</p>

          <div className="space-y-8 md:space-y-12">
            {sections.map((section, idx) => (
              <div key={idx} className="pb-8 border-b" style={{ borderColor: 'rgba(249, 249, 247, 0.08)' }}>
                <h2 className="font-serif font-bold text-2xl md:text-3xl mb-4" style={{ color: '#a8d5a2' }}>
                  {section.title}
                </h2>
                <p className="text-white/80 mb-4 leading-relaxed">{section.content}</p>
                {section.items && (
                  <ul className="space-y-2 ml-4">
                    {section.items.map((item, i) => (
                      <li key={i} className="text-white/70 text-sm flex items-start gap-2">
                        <span className="flex-shrink-0 mt-1.5">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            ))}
          </div>
        </div>
      </main>

      <WelcomeFooter />
    </div>
  );
}